name: value_pro
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  data:
    path: data
  sdk:
    path: sdk
  flutter_common:
    path: flutter_common

  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  device_info: ^2.0.0
  shared_preferences: '>=0.5.7+3 <2.0.0'
  rxdart: ^0.24.1
  get_it: ^7.1.3
  uuid: ^2.2.2
  global_configuration: ^1.6.0
  path_provider: ^2.0.0
  visibility_detector: ^0.1.5
  equatable: ^2.0.0
  flutter_svg: ^0.22.0
  flutter_xlider: ^3.4.0
  keyboard_visibility: 0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/cfg/
    - assets/images/png/
    - assets/images/svg/
#     - assets/licenses/
    - assets/locale/
    - assets/images/
    - assets/flags/
  fonts:
    - family: MyFont
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
